export const GET_COUNTRIES_LIST_REQUEST = "GET_COUNTRIES_LIST_REQUEST";
export const GET_COUNTRIES_LIST_SUCCESS = "GET_COUNTRIES_LIST_SUCCESS";
export const GET_COUNTRIES_LIST_FAILURE = "GET_COUNTRIES_LIST_FAILURE";
